[workspace]
members = [
    "sdb",
    "sdb-macros",
    # "sdb-macros/inner-macros",
    # "sdb-parser",
]

exclude = [
    "/sdb/example.db",
    "launch-demo-db.sh",
    "/sdb/example-db-content.sql",
]